blank_issues_enabled: false
contact_links:
  - name: 💬 General Discussion
    url: https://github.com/jkudjo/jkudjo/discussions
    about: Ask questions, share ideas, or start general discussions about the profile
  - name: 🔗 LinkedIn
    url: https://www.linkedin.com/in/philip-kumah-junior/
    about: Connect with Philip on LinkedIn for professional networking
